DROP DATABASE IF EXISTS expense_manager_web;
CREATE DATABASE expense_manager_web;
USE expense_manager_web;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(120) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,email_verified BOOLEAN DEFAULT FALSE,failed_login_count INT DEFAULT 0,locked_until DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE accounts (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,account_name VARCHAR(100) NOT NULL,account_type ENUM('Bank','Cash','UPI Wallet','Credit Card','Loan','Investment') DEFAULT 'Bank',account_subtype VARCHAR(50) DEFAULT 'Savings Account',bank_name VARCHAR(100),last4 VARCHAR(4),opening_balance DECIMAL(12,2) DEFAULT 0,current_balance DECIMAL(12,2) DEFAULT 0,credit_limit DECIMAL(12,2) DEFAULT 0,interest_rate DECIMAL(6,3) DEFAULT 0,institution_value DECIMAL(12,2) DEFAULT 0,last_reconciled_at TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE transactions (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,account_id INT NOT NULL,type ENUM('Income','Expense','Transfer') NOT NULL,category VARCHAR(100),amount DECIMAL(12,2) NOT NULL,description VARCHAR(255),transaction_date DATE NOT NULL,payment_method VARCHAR(50),receipt_path VARCHAR(255),statement_import_id INT NULL,transfer_to_account INT NULL,tags VARCHAR(255) NULL,recurring_transaction_id INT NULL,merchant VARCHAR(160) NULL,review_status ENUM('Cleared','Pending','Flagged') DEFAULT 'Cleared',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE);
CREATE TABLE budgets (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,category VARCHAR(100) NOT NULL,month_year VARCHAR(7) NOT NULL,budget_amount DECIMAL(12,2) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE savings_goals (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,goal_name VARCHAR(100) NOT NULL,target_amount DECIMAL(12,2) NOT NULL,saved_amount DECIMAL(12,2) DEFAULT 0,deadline DATE NULL,household_id INT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE goal_contributions (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,goal_id INT NOT NULL,account_id INT NOT NULL,action ENUM('Deposit','Withdraw') NOT NULL,amount DECIMAL(12,2) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY (goal_id) REFERENCES savings_goals(id) ON DELETE CASCADE,FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT);

CREATE TABLE statement_imports (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,account_id INT NOT NULL,file_name VARCHAR(255) NOT NULL,file_hash CHAR(64) NOT NULL,imported_rows INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY unique_statement (user_id,file_hash),FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT);

ALTER TABLE transactions ADD INDEX idx_statement_import_id (statement_import_id), ADD CONSTRAINT fk_transactions_statement_import FOREIGN KEY (statement_import_id) REFERENCES statement_imports(id) ON DELETE SET NULL;
