import React,{useEffect,useState}from"react";
import api from"../services/api";
import{Notice,ConfirmDialog}from"../components/Notice";
const CATEGORY_OPTIONS={Bank:["Savings Account","Current Account","Salary Account"],Cash:["Cash"],"UPI Wallet":["PhonePe","Google Pay","Paytm","Other Wallet"],"Credit Card":["Credit Card"],Loan:["Home Loan","Vehicle Loan","Education Loan","Personal Loan"],Investment:["Mutual Fund","Stocks","Fixed Deposit","Retirement"]};
const emptyForm={account_name:"",account_type:"Bank",account_subtype:"Savings Account",bank_name:"",last4:"",opening_balance:"",credit_limit:"",interest_rate:"",institution_value:""};
export default function Accounts(){
 const[rows,setRows]=useState([]);const[form,setForm]=useState(emptyForm);const[editing,setEditing]=useState(null);
 const[message,setMessage]=useState(null),[deleteTarget,setDeleteTarget]=useState(null),[reconcileTarget,setReconcileTarget]=useState(null);
 const load=async()=>setRows((await api.get("/accounts")).data);useEffect(()=>{load()},[]);
 const changeType=type=>setForm({...form,account_type:type,account_subtype:CATEGORY_OPTIONS[type][0],bank_name:type==="Cash"?"Cash":form.bank_name});
 const submit=async e=>{e.preventDefault();setMessage(null);if(!form.account_name||(!editing&&form.opening_balance===""))return setMessage({type:"warning",text:"Account name and opening balance are required"});if(form.last4&&form.last4.length!==4)return setMessage({type:"warning",text:"Enter exactly 4 account digits"});try{if(editing){await api.put(`/accounts/${editing}`,form);setMessage({type:"success",text:"Account updated"})}else{await api.post("/accounts",form);setMessage({type:"success",text:"Account added"})}setEditing(null);setForm(emptyForm);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not save account"})}};
 const startEdit=a=>{setEditing(a.id);setForm({account_name:a.account_name,account_type:a.account_type,account_subtype:a.account_subtype||CATEGORY_OPTIONS[a.account_type][0],bank_name:a.bank_name||"",last4:a.last4||"",opening_balance:a.opening_balance,credit_limit:a.credit_limit||"",interest_rate:a.interest_rate||"",institution_value:a.institution_value||""});window.scrollTo({top:0,behavior:"smooth"})};
 const cancelEdit=()=>{setEditing(null);setForm(emptyForm)};
 const remove=async()=>{if(!deleteTarget)return;try{await api.delete(`/accounts/${deleteTarget.id}`);setMessage({type:"success",text:"Account deleted"});setDeleteTarget(null);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not delete account"});setDeleteTarget(null)}};
 const reconcile=async e=>{e.preventDefault();try{const{data}=await api.post(`/accounts/${reconcileTarget.id}/reconcile`,{actual_balance:reconcileTarget.actual_balance});setMessage({type:"success",text:`Reconciled. Adjustment: Rs ${Number(data.difference).toLocaleString("en-IN")}`});setReconcileTarget(null);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not reconcile account"})}};
 const total=rows.reduce((s,r)=>s+(["Loan","Credit Card"].includes(r.account_type)?-Math.abs(Number(r.institution_value||r.current_balance||0)):Number(r.institution_value||r.current_balance||0)),0);const icon=t=>t==="Cash"?"bi-cash":t==="UPI Wallet"?"bi-phone":t==="Credit Card"?"bi-credit-card":t==="Loan"?"bi-house-dash":t==="Investment"?"bi-graph-up-arrow":"bi-bank";
 return <><div className="dashboard-header"><div><h2 className="page-title mb-1">Accounts</h2><p className="text-muted mb-0">Manage bank, cash, UPI wallet and credit-card accounts.</p></div><div className="quick-date"><i className="bi bi-wallet2"/>₹{total.toLocaleString()}</div></div>
 <Notice message={message} onClose={()=>setMessage(null)}/>
 <div className="panel"><h5 className="fw-bold mb-3">{editing ? "Edit Account" : "Add New Account"}</h5><form className="row g-3" onSubmit={submit}>
 <div className="col-lg-3 col-md-6"><label className="form-label">Account Name</label><input className="form-control" placeholder="SBI Savings" value={form.account_name} onChange={e=>setForm({...form,account_name:e.target.value})}/></div>
 <div className="col-lg-2 col-md-6"><label className="form-label">Type</label><select className="form-select" value={form.account_type} onChange={e=>changeType(e.target.value)}>{Object.keys(CATEGORY_OPTIONS).map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="col-lg-2 col-md-6"><label className="form-label">Account Category</label><select className="form-select" value={form.account_subtype} onChange={e=>setForm({...form,account_subtype:e.target.value})}>{CATEGORY_OPTIONS[form.account_type].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="col-lg-2 col-md-6"><label className="form-label">Bank / Wallet Name</label><input className="form-control" placeholder="SBI / HDFC" disabled={form.account_type==="Cash"} value={form.bank_name} onChange={e=>setForm({...form,bank_name:e.target.value})}/></div>
 <div className="col-lg-1 col-md-6"><label className="form-label">Last 4</label><input className="form-control" maxLength="4" placeholder="1234" value={form.last4} onChange={e=>setForm({...form,last4:e.target.value.replace(/\D/g,"")})}/></div>
 <div className="col-lg-2 col-md-6"><label className="form-label">Opening Balance</label><input type="number" className="form-control" placeholder="10000" disabled={Boolean(editing)} value={form.opening_balance} onChange={e=>setForm({...form,opening_balance:e.target.value})}/></div>
 {form.account_type==="Credit Card"&&<div className="col-lg-2 col-md-6"><label className="form-label">Credit Limit</label><input type="number" className="form-control" value={form.credit_limit} onChange={e=>setForm({...form,credit_limit:e.target.value})}/></div>}
 {["Loan","Investment"].includes(form.account_type)&&<><div className="col-lg-2 col-md-6"><label className="form-label">Current Value</label><input type="number" className="form-control" value={form.institution_value} onChange={e=>setForm({...form,institution_value:e.target.value})}/></div><div className="col-lg-2 col-md-6"><label className="form-label">Interest / Return %</label><input type="number" step="0.001" className="form-control" value={form.interest_rate} onChange={e=>setForm({...form,interest_rate:e.target.value})}/></div></>}
 <div className="col-12 d-flex gap-2"><button className="btn btn-primary px-4"><i className={`bi ${editing ? "bi-check-circle" : "bi-plus-circle"} me-2`}/>{editing ? "Save Changes" : "Add Account"}</button>{editing&&<button type="button" className="btn btn-outline-secondary" onClick={cancelEdit}>Cancel</button>}</div></form></div>
 <div className="row g-3 mt-2">{rows.length===0?<div className="col-12"><div className="panel text-center text-muted">No accounts added yet.</div></div>:rows.map(a=><div className="col-lg-3 col-md-6" key={a.id}><div className="account-card"><div className="d-flex justify-content-between"><div><p className="text-muted mb-1">{a.account_subtype||a.account_type}</p><h5 className="fw-bold">{a.account_name}</h5><small>{a.bank_name||"N/A"}</small></div><div className="account-icon"><i className={`bi ${icon(a.account_type)}`}/></div></div><h3 className="fw-bold mt-4">₹{Number(a.current_balance||0).toLocaleString()}</h3><div className="d-flex justify-content-between mt-3"><small>{a.account_type}</small><small>{a.last4?"XXXX"+a.last4:"N/A"}</small></div></div></div>)}</div>
 <div className="panel mt-4"><h5 className="fw-bold mb-3">Account List</h5><div className="table-responsive"><table className="table table-hover modern-table"><thead><tr><th>Name</th><th>Type</th><th>Category</th><th>Bank/Wallet</th><th>Account</th><th>Opening</th><th>Current</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.account_name}</td><td><span className="badge bg-primary">{r.account_type}</span></td><td>{r.account_subtype||"—"}</td><td>{r.bank_name}</td><td>{r.last4?"XXXX"+r.last4:"N/A"}</td><td>₹{Number(r.opening_balance||0).toLocaleString()}</td><td className="fw-bold">₹{Number(r.current_balance||0).toLocaleString()}</td><td><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-success" onClick={()=>setReconcileTarget({...r,actual_balance:r.current_balance})} title="Reconcile account"><i className="bi bi-check2-square"/></button><button className="btn btn-sm btn-outline-primary" onClick={()=>startEdit(r)} title="Edit account"><i className="bi bi-pencil"/></button><button className="btn btn-sm btn-outline-danger" onClick={()=>setDeleteTarget(r)} title="Delete account"><i className="bi bi-trash"/></button></div></td></tr>)}</tbody></table></div></div>
 <ConfirmDialog state={deleteTarget&&{title:"Delete account",message:`Delete ${deleteTarget.account_name}?`,confirmText:"Delete"}} onCancel={()=>setDeleteTarget(null)} onConfirm={remove}/>
 {reconcileTarget&&<div className="modal-backdrop-custom"><div className="goal-dialog"><div className="d-flex justify-content-between"><h4>Reconcile Account</h4><button className="btn-close" onClick={()=>setReconcileTarget(null)}/></div><p className="text-muted">{reconcileTarget.account_name}</p><form onSubmit={reconcile}><label className="form-label">Statement balance</label><input autoFocus type="number" step="0.01" className="form-control mb-3" value={reconcileTarget.actual_balance} onChange={e=>setReconcileTarget({...reconcileTarget,actual_balance:e.target.value})}/><button className="btn btn-success w-100">Save Adjustment</button></form><small className="text-muted d-block mt-2">An adjustment transaction will be recorded for the difference.</small></div></div>}</>
}
