import React,{useEffect,useState}from"react";
import api from"../services/api";
import{Notice,ConfirmDialog}from"../components/Notice";
const CATEGORIES=["Food","Travel","Shopping","Bills","Rent","College","Medical","Entertainment","Fuel","EMI","Groceries","Utilities","Insurance","Education","Personal Care","Other"];
const fresh=()=>({category:"Food",month_year:new Date().toISOString().slice(0,7),budget_amount:""});
export default function Budget(){
 const[rows,setRows]=useState([]),[form,setForm]=useState(fresh()),[editing,setEditing]=useState(null);
 const[message,setMessage]=useState(null),[deleteTarget,setDeleteTarget]=useState(null);
 const load=async()=>setRows((await api.get("/budgets")).data);useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setMessage(null);if(Number(form.budget_amount)<=0)return setMessage({type:"warning",text:"Enter a valid budget amount"});try{if(editing){await api.put("/budgets/"+editing,form);setMessage({type:"success",text:"Budget updated"})}else{await api.post("/budgets",form);setMessage({type:"success",text:"Budget added"})}setEditing(null);setForm(fresh());load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not save budget"})}};
 const edit=r=>{setEditing(r.id);setForm({category:r.category,month_year:r.month_year,budget_amount:r.budget_amount});window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async()=>{if(!deleteTarget)return;try{await api.delete("/budgets/"+deleteTarget.id);setMessage({type:"success",text:"Budget deleted"});setDeleteTarget(null);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not delete budget"});setDeleteTarget(null)}};
 const warnings=rows.filter(r=>Number(r.spent)/Number(r.budget_amount)>=.8);
 return <><div className="dashboard-header"><div><h2 className="page-title mb-1">Budget Planner</h2><p className="text-muted mb-0">Set monthly limits and receive warnings before overspending.</p></div></div>
 <Notice message={message} onClose={()=>setMessage(null)}/>
 {warnings.length>0&&<div className="budget-alert"><i className="bi bi-exclamation-triangle"/><div><strong>Budget attention needed</strong><p>{warnings.map(x=>x.category).join(", ")} {warnings.length===1?"is":"are"} at or above 80% usage.</p></div></div>}
 <div className="panel"><h5 className="fw-bold mb-3">{editing?"Edit Budget":"Add Budget"}</h5><form className="row g-3" onSubmit={submit}><div className="col-md-4"><label className="form-label">Category</label><select className="form-select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div><div className="col-md-3"><label className="form-label">Month</label><input className="form-control" type="month" value={form.month_year} onChange={e=>setForm({...form,month_year:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Budget Amount</label><input className="form-control" type="number" min="1" placeholder="5000" value={form.budget_amount} onChange={e=>setForm({...form,budget_amount:e.target.value})}/></div><div className="col-md-2 d-flex align-items-end gap-2"><button className="btn btn-primary flex-grow-1">{editing?"Save":"Add"}</button>{editing&&<button type="button" className="btn btn-outline-secondary" onClick={()=>{setEditing(null);setForm(fresh())}}>Cancel</button>}</div></form></div>
 <div className="row g-3 mt-1">{rows.map(r=>{const spent=Number(r.spent),limit=Number(r.budget_amount),raw=Math.round(spent/limit*100||0),pct=Math.min(100,raw),remaining=Math.max(0,limit-spent),status=raw>100?"Exceeded":raw>=80?"Near Limit":"On Track";return <div className="col-lg-4 col-md-6" key={r.id}><div className="budget-card"><div className="d-flex justify-content-between"><div><small>{r.month_year}</small><h4>{r.category}</h4></div><span className={"badge "+(status==="Exceeded"?"bg-danger":status==="Near Limit"?"bg-warning text-dark":"bg-success")}>{status}</span></div><div className="budget-numbers"><strong>₹{spent.toLocaleString()}</strong><span>of ₹{limit.toLocaleString()}</span></div><div className="progress"><div className={"progress-bar "+(status==="Exceeded"?"bg-danger":status==="Near Limit"?"bg-warning":"bg-primary")} style={{width:pct+"%"}}>{raw}%</div></div><p className="budget-remaining">{status==="Exceeded"?"Over by ₹"+(spent-limit).toLocaleString():"₹"+remaining.toLocaleString()+" remaining"}</p><div className="budget-advice">{status==="Exceeded"?"Pause non-essential "+r.category+" spending.":status==="Near Limit"?"Only 20% or less remains for this month.":"Your spending is within the planned limit."}</div><div className="d-flex gap-2 mt-3"><button className="btn btn-sm btn-outline-primary" onClick={()=>edit(r)}><i className="bi bi-pencil me-1"/>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={()=>setDeleteTarget(r)}><i className="bi bi-trash me-1"/>Delete</button></div></div></div>})}</div>
 <ConfirmDialog state={deleteTarget&&{title:"Delete budget",message:`Delete ${deleteTarget.category} budget?`,confirmText:"Delete"}} onCancel={()=>setDeleteTarget(null)} onConfirm={remove}/></>
}
