import React,{useEffect,useState}from"react";
import api from"../services/api";
import{Notice,ConfirmDialog}from"../components/Notice";
const blank={goal_name:"",target_amount:"",deadline:""};
export default function Goals(){
 const[rows,setRows]=useState([]),[accounts,setAccounts]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[move,setMove]=useState(null),[history,setHistory]=useState(null);
 const[message,setMessage]=useState(null),[deleteTarget,setDeleteTarget]=useState(null);
 const load=async()=>{const[g,a]=await Promise.all([api.get("/goals"),api.get("/accounts")]);setRows(g.data);setAccounts(a.data)};useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setMessage(null);if(!form.goal_name||Number(form.target_amount)<=0)return setMessage({type:"warning",text:"Enter a goal name and valid target"});try{if(editing){await api.put("/goals/"+editing,form);setMessage({type:"success",text:"Goal updated"})}else{await api.post("/goals",form);setMessage({type:"success",text:"Goal added"})}setEditing(null);setForm(blank);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not save goal"})}};
 const edit=g=>{setEditing(g.id);setForm({goal_name:g.goal_name,target_amount:g.target_amount,deadline:g.deadline||""});window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async()=>{if(!deleteTarget)return;try{await api.delete("/goals/"+deleteTarget.id);setMessage({type:"success",text:"Goal deleted"});setDeleteTarget(null);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not delete goal"});setDeleteTarget(null)}};
 const openMove=(g,action)=>setMove({goal:g,action,account_id:accounts[0]?.id||"",amount:""});
 const saveMove=async e=>{e.preventDefault();try{await api.post("/goals/"+move.goal.id+"/contributions",move);setMessage({type:"success",text:move.action==="Deposit"?"Money saved to goal":"Money returned to account"});setMove(null);load()}catch(err){setMessage({type:"danger",text:err.response?.data?.error||"Could not update savings"})}};
 const showHistory=async g=>{const{data}=await api.get("/goals/"+g.id+"/contributions");setHistory({goal:g,rows:data})};
 const totalSaved=rows.reduce((sum,g)=>sum+Number(g.saved_amount||0),0),totalTarget=rows.reduce((sum,g)=>sum+Number(g.target_amount||0),0),totalRemaining=Math.max(0,totalTarget-totalSaved);
 return <><div className="dashboard-header"><div><h2 className="page-title mb-1">Savings Goals</h2><p className="text-muted mb-0">Move money from your accounts toward the things that matter.</p></div></div>
 <Notice message={message} onClose={()=>setMessage(null)}/>
 <div className="row g-3 mb-3"><div className="col-md-4"><div className="mini-stat income-stat"><span>Saved in Goals</span><h4>Rs {totalSaved.toLocaleString()}</h4></div></div><div className="col-md-4"><div className="mini-stat balance-stat"><span>Goal Target</span><h4>Rs {totalTarget.toLocaleString()}</h4></div></div><div className="col-md-4"><div className="mini-stat"><span>Still Needed</span><h4>Rs {totalRemaining.toLocaleString()}</h4><small>Savings are tracked separately from expenses.</small></div></div></div>
 <div className="panel"><h5 className="fw-bold mb-3">{editing?"Edit Goal":"Create a Goal"}</h5><form className="row g-3" onSubmit={submit}><div className="col-md-4"><label className="form-label">Goal Name</label><input className="form-control" placeholder="MacBook Pro" value={form.goal_name} onChange={e=>setForm({...form,goal_name:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Target Amount</label><input type="number" min="1" className="form-control" placeholder="120000" value={form.target_amount} onChange={e=>setForm({...form,target_amount:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Target Date</label><input className="form-control" type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></div><div className="col-md-2 d-flex align-items-end gap-2"><button className="btn btn-primary flex-grow-1">{editing?"Save":"Add Goal"}</button>{editing&&<button type="button" className="btn btn-outline-secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div></form></div>
 <div className="row g-3 mt-1">{rows.length===0?<div className="col-12"><div className="panel text-center text-muted">No savings goals yet.</div></div>:rows.map(g=>{const saved=Number(g.saved_amount),target=Number(g.target_amount),pct=Math.min(100,Math.round(saved/target*100||0)),remaining=Math.max(0,target-saved),done=pct>=100;return <div className="col-xl-4 col-md-6" key={g.id}><div className={"goal-card "+(done?"goal-complete":"")}><div className="d-flex justify-content-between"><span className="goal-icon"><i className={"bi "+(done?"bi-check-lg":"bi-bullseye")}/></span><span className={"badge "+(done?"bg-success":"bg-primary")}>{done?"Completed":pct+"% funded"}</span></div><h4>{g.goal_name}</h4><p className="goal-money">₹{saved.toLocaleString()} <small>of ₹{target.toLocaleString()}</small></p><div className="progress goal-progress"><div className={"progress-bar "+(done?"bg-success":"")} style={{width:pct+"%"}}/></div><div className="goal-meta"><span>₹{remaining.toLocaleString()} remaining</span><span>{g.deadline||"No deadline"}</span></div><div className="d-flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-success" disabled={done||!accounts.length} onClick={()=>openMove(g,"Deposit")}><i className="bi bi-plus-circle me-1"/>Add Money</button><button className="btn btn-sm btn-outline-warning" disabled={saved<=0||!accounts.length} onClick={()=>openMove(g,"Withdraw")}><i className="bi bi-arrow-counterclockwise me-1"/>Withdraw</button><button className="btn btn-sm btn-outline-secondary" onClick={()=>showHistory(g)} title="History"><i className="bi bi-clock-history"/></button><button className="btn btn-sm btn-outline-primary" onClick={()=>edit(g)} title="Edit"><i className="bi bi-pencil"/></button><button className="btn btn-sm btn-outline-danger" onClick={()=>setDeleteTarget(g)} title="Delete"><i className="bi bi-trash"/></button></div>{!accounts.length&&<small className="text-danger d-block mt-2">Add an account before saving money.</small>}</div></div>})}</div>
 <ConfirmDialog state={deleteTarget&&{title:"Delete goal",message:`Delete ${deleteTarget.goal_name}?`,confirmText:"Delete"}} onCancel={()=>setDeleteTarget(null)} onConfirm={remove}/>
 {move&&<div className="modal-backdrop-custom"><div className="goal-dialog"><div className="d-flex justify-content-between"><h4>{move.action==="Deposit"?"Add Goal Savings":"Withdraw Goal Savings"}</h4><button className="btn-close" onClick={()=>setMove(null)}/></div><p className="text-muted">{move.goal.goal_name}</p><form onSubmit={saveMove}><label className="form-label">{move.action==="Deposit"?"Take money from":"Return money to"}</label><select className="form-select mb-3" value={move.account_id} onChange={e=>setMove({...move,account_id:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.account_name} — ₹{Number(a.current_balance).toLocaleString()}</option>)}</select><label className="form-label">Amount</label><input autoFocus required type="number" min="1" className="form-control mb-3" value={move.amount} onChange={e=>setMove({...move,amount:e.target.value})}/><button className={"btn w-100 "+(move.action==="Deposit"?"btn-success":"btn-warning")}>{move.action==="Deposit"?"Save to Goal":"Return to Account"}</button></form></div></div>}
 {history&&<div className="modal-backdrop-custom"><div className="goal-dialog history-dialog"><div className="d-flex justify-content-between"><h4>{history.goal.goal_name} History</h4><button className="btn-close" onClick={()=>setHistory(null)}/></div><div className="table-responsive mt-3"><table className="table"><thead><tr><th>Date</th><th>Account</th><th>Action</th><th>Amount</th></tr></thead><tbody>{history.rows.length?history.rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleDateString()}</td><td>{x.account_name}</td><td><span className={"badge "+(x.action==="Deposit"?"bg-success":"bg-warning text-dark")}>{x.action==="Deposit"?"Saved":"Returned"}</span></td><td>₹{Number(x.amount).toLocaleString()}</td></tr>):<tr><td colSpan="4" className="text-center text-muted">No activity yet.</td></tr>}</tbody></table></div></div></div>}</>
}
